### ISSUE TITLE
The bug in BRATS

### ISSUE THREAD

**Issue by YiboSun2023** [Luffy03/Large-Scale-Medical#1] opened 2024-10-15 03:51 UTC
After running the code in BRATS21 demo, I wonder why the result of Dice_ET returns the value of nan in the validation part?

**Comment by Luffy03** [comment] 2024-10-15 03:53
Hi, thanks for your attention to our work. Do you mean the codes in https://github.com/Luffy03/Large-Scale-Medical/tree/main/Downstream/monai/BRATS21? Would you please share more details about training?

**Comment by YiboSun2023** [comment] 2024-10-15 03:57
<img width="413" alt="屏幕截图 2024-10-15 142512" src="https://github.com/user-attachments/assets/4962afcc-6acc-4bce-b0b3-db4d6148b0f5">
Just this code inside. I have altered some parameters inside my parser code, this is the training result. Is it same with your code?

**Comment by Luffy03** [comment] 2024-10-15 03:58
Hi, what parameters have you altered? I am uploading checkpoints and training logs to https://pan.baidu.com/s/1w75cJWoWfCt2FSjMDYl1FA?pwd=r1rp#list/path=%2F. you may have a look.

**Comment by Luffy03** [comment] 2024-10-15 04:01
My training log is as 
[20240725_073644_90.23.txt](https://github.com/user-attachments/files/17372309/20240725_073644_90.23.txt)

**Comment by YiboSun2023** [comment] 2024-10-15 04:02
I have changed the out_channels into 3, and load the pretraining model as your old version model. Is it true to run this code?

**Comment by Luffy03** [comment] 2024-10-15 04:06
oh no, the out_channels should be 4 (one background class, three foreground classes). please directly use our updated codes and don't change the parameters.

**Comment by YiboSun2023** [comment] 2024-10-15 04:10
ValueError: number of channels for target is neither 1 (without one-hot encoding) nor the same as input, got shape torch.Size([1, 4, 128, 128, 128]) and torch.Size([1, 3, 128, 128, 128]). It happens the Value error when set the out_channels as 4, so what I need to change?

**Comment by Luffy03** [comment] 2024-10-15 04:19
Hi, I cannot understand your problem. Seems you did not use our codes. You need to use the label_transform functions at https://github.com/Luffy03/Large-Scale-Medical/blob/main/Downstream/monai/BRATS21/utils/data_utils.py. The above errors may be caused by wrong label transform. Would you please download the entire repo 'Downstream/monai/BRATS21' for implementation?

Our checkpoints and training logs are uploaded to https://pan.baidu.com/s/1w75cJWoWfCt2FSjMDYl1FA?pwd=r1rp#list/path=%2F now, you may have a look

**Comment by YiboSun2023** [comment] 2024-10-15 04:23
Okey, I will try again. Thank you for your suggestion.

**Comment by Luffy03** [comment] 2024-10-15 04:24
Hi you can find that in https://github.com/Luffy03/Large-Scale-Medical/blob/bf53012f6d3817d8e10f88383df7a2c3bcd595b7/Downstream/monai/BRATS21/utils/data_utils.py#L210. The labels are transformed to 4 channels, so your output_chanels should be 4.

**Comment by YiboSun2023** [comment] 2024-10-15 04:35
Okey, thank you for your kind remind. I am too careless for carrying on reproducing.

**Comment by Luffy03** [comment] 2024-10-15 04:41
No problems! Your attention to our work encourages me a lot! Feel free to raise any issues and I will reply to it as soon as possible. And we would be grateful if you could consider giving us a star if you find our codes useful (^o^)/

**Comment by Luffy03** [comment] 2024-10-25 06:15
Hi yibo, I would like to close this issue. Feel free to raise new issues if you have any problems. Thanks!

**Closed by Luffy03** 2024-10-25 06:15 UTC
